server:
  port: 8082

spring:
  application:
    name: post-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/web3_community_posts}

logging:
  level:
    com.web3community: DEBUG