apiVersion: v1
kind: Secret
metadata:
  name: web3-secrets
  namespace: web3-community
type: Opaque
stringData:
  JWT_SECRET: "dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3QgdG9rZW4gZ2VuZXJhdGlvbg=="
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "rootpassword"
  MYSQL_ROOT_PASSWORD: "rootpassword"
  REDIS_PASSWORD: ""
